import Head from 'next/head'
import styles from '../styles/Home.module.scss'
import Header from 'components/Header'
import Footer from 'components/Footer'
import { CardOne, CardTwo } from 'components/Cards'
import { CardThree } from '../src/components/Cards'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>NLW Esports</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      <main className={styles.main}>
        <CardOne />
        <CardTwo />
        <CardThree />
      </main>

      <Footer />
    </div>
  )
}
